### ISSUE TITLE
how can i run the amfbrowser.exe on a linux system?

### ISSUE THREAD

**Issue by PaulLiuYZ** [SchornacklabSLCU/amfinder#10]
i have followed the instructions and obtained the amfbrowser.exe file on a ubuntu system, but i cannot run it with the "amfbrowser my_name.jpg", i cannot open it with double clicking it . So ,how can i run the exe file?

**Comment by SchornacklabSLCU** [comment]
Hello, to run the program you need to type `./amfbrowser.exe my_name.jpg`. The extension (`.exe`) is required if it is part of the executable name, and you need to specify the path (in my example, `.` stands for the current directory) if `amfbrowser` is not in `$PATH`. Please let me know if that works for you.

**Comment by PaulLiuYZ** [comment]
> Hello, to run the program you need to type `./amfbrowser.exe my_name.jpg`. The extension (`.exe`) is required if it is part of the executable name, and you need to specify the path (in my example, `.` stands for the current directory) if `amfbrowser` is not in `$PATH`. Please let me know if that works for you.

Oh, i see. I have run it sucessfully now. Thanks a lot!!!
