### ISSUE TITLE
Had to do code changes for MacOS

### ISSUE THREAD

**Issue by matevzl533** [SchornacklabSLCU/amfinder#12]
Hello, 

first I like to say it's a great pipeline for AMF colonisation analysis.

I am reporting two changes that I had to do when installing (MacOS 10.14.6) - don't know if this is due to OS or updated libraries or something else:

In **amfinder_model.py** I was getting an error until I changed the line 53 from:
`from keras.optimizers import Adam`
to:
`from keras.optimizers import adam_v2`

Got the fix from: https://stackoverflow.com/questions/62707558/importerror-cannot-import-name-adam-from-keras-optimizers

In **amfinder_superresolution.py** I had to change the line 36 from:
`from keras.engine.network import Network`
to:
`from tf_agents.networks import network`
after instaling tensorflow agents.
Got the fix from: https://www.tensorflow.org/agents/tutorials/8_networks_tutorial

Now everything works. Maybe this will help someone in the same situation.

**Comment by SchornacklabSLCU** [comment]
Hello,

Thanks a lot for reporting this.

Could you please check which version of Keras you are running? In your first link I read that `adam_v2` is used with Keras 2.5.0 (while `amfinder` was designed with Keras 2.3). If you are able to confirm, I will add comments directly in the code mentioning the fix in case other people encounter the same problem.

**Comment by matevzl533** [comment]
Hello,

I am using Keras 2.6.0 version (released on 9th of August 2021). So probably not a macOS thing, but rather due to changes in different Keras versions.

**Comment by SchornacklabSLCU** [comment]
Yes, likely. I used an older version due to [an issue with class weights](https://github.com/tensorflow/tensorflow/issues/40457) that affects training. Thanks for reporting the changes, I will add comments to the files for future development of the application.
