### ISSUE TITLE
Getting the amfbrowser.exe to run 

### ISSUE THREAD

**Issue by florakwang** [SchornacklabSLCU/amfinder#15]
Hi sorry to bother, I was just wondering how one would go about getting the amfbrowser.exe to run on a newer version of MacOS? The one that is in the folder is Catalina64.exe but I have Big Sur. Is there a way I would be able to change the exe file to get it to run on my laptop? 
Thank you so much for your help in advance.

**Comment by EEvangelisti** [comment]
Hello, thanks for your interest in AMFinder. I will see whether I can get access to a newer MacOS system and provide you with a precompiled binary for Big Sur. Otherwise, you can follow the manual compilation and installation instructions described in the README file. I am happy to assist with that.

**Comment by EEvangelisti** [comment]
Hello, unfortunately, I could not find a machine running Big Sur to compile `amfbrowser` You will have to compile it by yourself. Please follow the instructions on the README file.

**Comment by florakwang** [comment]
Thank you for your help! 
I was wondering if you mind pointing to exactly where and what I should follow? I did install homebrew according to the instructions already, but the amfbrowser.exe line wouldn't run properly on my terminal.  
Thank you again!

**Comment by SchornacklabSLCU** [comment]
Hello,

The provided amfbrowser.exe won't work so you can delete it. Then, you need
to compile amfbrowser from sources following these steps (copy/paste from
the README file):


   1.

   Download and install OPAM from the official webwsite
   <https://opam.ocaml.org/doc/Install.html> or from your package manager.
   2.

   Open a terminal in the amfbrowser folder and run the command: export
   OPAM=<path>, replacing <path> with the path to the opam program. Then,
   run the command ./install.sh to install amfbrowser dependencies and
   compile amfbrowser.exe. Should the variable OPAM not be set, the script
   will use the output of which opam. If needed, add executable permissions
   to the installation file with: chmod +x install.sh. Follow the
   instructions on the screen and reply yes to the questions asked during opam
   installation and configuration.

Note: You may need to install development packages such as libgtk2.0-dev
 and libgtksourceview2.0-dev. Users with miniconda
<https://docs.conda.io/en/latest/miniconda.html> or similar tool suite
installed may encounter problems if their PATH variable has been altered.
You may have to temporarily mask miniconda directory from your PATH variable
by running PATH=<modified_path> opam install ....

Please let me know if that works for you.

Best regards,
Edouard

Le sam. 22 janv. 2022 à 00:30, florakwang ***@***.***> a
écrit :

> Thank you for your help!
> I was wondering if you mind pointing to exactly where and what I should
> follow? I did install homebrew according to the instructions already, but
> the amfbrowser.exe line wouldn't run properly on my terminal.
> Thank you again!
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>


-- 

*Dr. Edouard Evangelisti*

*Postdoctoral Research Associate*

*Sainsbury Laboratory, Cambridge University (SLCU)*


*Bateman StreetCambridge CB2 1LR (United Kingdom)*

**Comment by florakwang** [comment]
Thank you so much! I was able to get it to work eventually!
