### ISSUE TITLE
Training problems 

### ISSUE THREAD

**Issue by florakwang** [SchornacklabSLCU/amfinder#16]
Hi, 
Sorry to bother you, I was wondering whether the program is able to train an entire folder of annotated images at once or would I have to train it image by image? Somehow when I do "./amf train folder_name" it says that my images in the folder are not annotated for some reason, but when I train it image by image by drag and drop, it does not throw that error. (All images along with the zip files are in the same folder that I gave it). I also tried giving it multiple images by simple drag and drop, but the program only seems to take the first image as input and ignores the rest.

I also get the following error for some images that I input, which I'm not exactly sure why, since I annotated them all in the same manner. 
ValueError: `class_weight` must contain all classes in the data. The classes {2} exist in the data but not in `class_weight`.

Any insight would be much appreciated. Thank you so much for all your help!

**Comment by EEvangelisti** [comment]
Hello,
Yes, it does. The command is `amf train <parameters> <images>` which translates into `amf train folder_name/*jpg` in your case. If you only provide `folder_name`, it will assume `folder_name` is an image and throw an error.
The second error sounds more unusual to me. Once you confirm the first issue is solved, would you mind sharing an annotated picture that triggers the `class_weight` error? That would be great. Cheers.

**Comment by florakwang** [comment]
Hi, 
Thank you so much for your reply! 
I have images of different species of plants colonized by AM saved in different folders, and while "*/jpg" did fix the problem for some of the folders, it did not for others. I was thus wondering whether there are any initial requirements to the images and whether that could have caused the problems? All of them are in jpg format but some are bigger than others. I also tried changing the image name, re-annotating, moving the images into the folder that worked, but neither of those helped, so I would really appreciate some insight! Thank you!  

And I have attached an annotated figure that caused the program to throw the class_weight error. I think its possibly because I didn't assign any M- classes? But does that mean I have to use images with all classes present? I can try to do this for CNN1, but for CNN2 we don't necessarily see all four features (i.e. arbuscules, vesicles, intradical hyphae and the hypophodium) in one image, so I was wondering whether there's a trick around not having to have all classes annotated in one image?
<img width="534" alt="Screen Shot 2022-02-08 at 12 55 43 PM" src="https://user-images.githubusercontent.com/98064133/153097214-cbb0fcd6-5a9b-41cc-bcde-b34570c0f518.png">

Sorry for the long questions and thank you so much for all your help! I really appreciate it!

**Comment by EEvangelisti** [comment]
Hi,

Would you be able to share a picture and zip file for both situations (one
that is not used for training, and one that triggers class_weight error)? I
would need the actual images to test them on my machine (not a screenshot).
I suspect the second case to be a bug. I am not sure about the first case.
Please use either Dropbox or any other file sharing tool if the images are
too large for an email. That would be great!

Many thanks.

Best regards,
Edouard

**Comment by florakwang** [comment]
Hi Edouard, 

Thanks so much for your instant reply again! I really appreciate it! 
Here's a google drive link to the images that work/don't work (for the annotations) and two images that throw the class_weight error:
https://drive.google.com/drive/folders/1GhKhNZZ-MTZcMIAudE1atHcl7v6VmRIR?usp=sharing

Thank you so much for your help again! Really appreciate it! 

Sincerely,
Flora

**Comment by EEvangelisti** [comment]
Hi Flora,

Thanks for reporting this bug. I fixed the problem with class weights. 

I never used AMFinder with fluorescent pictures before, hence I always had all classes in the CNN1 training dataset. The new `amf` will handle missing classes. Please download the new version, unzip it, then just replace the old `amfinder_train.py` with the new one (there is no need to reinstall `amf`). I could start training with images from both directories.

Please let me know if that works for you.

Cheers,
Edouard

**Comment by florakwang** [comment]
Hi Edouard,

Thank you so much for all your help! I really appreciate it! 
It works now! 

Sincerely,
Flora

**Comment by EEvangelisti** [comment]
Hi Flora,

I am glad this was helpful. Good luck with your experiments!

Best regards,
Edouard
