### ISSUE TITLE
amfbrowser

### ISSUE THREAD

**Issue by Biozac** [SchornacklabSLCU/amfinder#31]
Hi,
Thanks for this amazing software. I got AMFinder to successfully generate a prediction for a test image, however when I attempt to open the prediction on the browser, I cannot select "ok" (or even "cancel"). The program freezes.

On WSL I get this notice when I open the browser:
`(amfbrowser.exe:79): Gtk-CRITICAL **: 16:30:43.574: gtk_window_realize_icon: assertion 'info->icon_pixmap == NULL' failed`

![image](https://user-images.githubusercontent.com/99962215/227993815-4dac5af3-373c-4c9f-90dc-c71fcf09a0aa.png)

Would appreciate advice, thanks!

**Comment by Biozac** [comment]
I'd made a mistake with converting predictions I think! All working now :)

**Comment by rob-ferg** [comment]
Hello,

I have run into the same issue, where I cannot click on any of the buttons in the pop-up for selecting a prediction file. Can you describe how you fixed the predictions? How did this fix the initial issue?

Thanks!
