### ISSUE TITLE
Command 'amf' not found

### ISSUE THREAD

**Issue by mattsiel** [SchornacklabSLCU/amfinder#32]
Having this error when I try to run the application. 

I have followed the instructions for setting up on windows. 
I downloaded WSL and python3.9, then ran ./install.sh and got the confirmation message at the end of the script.

I have the virtual environment set up and running when I run amf.

 Did I miss something during the installation?

**Comment by EEvangelisti** [comment]
Hello,

Apologies for the late reply.
In Linux terminal, you need to type "./amf" to run the amf command. Otherwise, the terminal will look for system folders only, where amf is not present.

I hope this solves your issue.

Best wishes,
Edouard

**Comment by EEvangelisti** [comment]
I assume the issue is now solved. Feel free to reopen it if needed.
