### ISSUE TITLE
Cannot select prediction file to import (amfbrowser)

### ISSUE THREAD

**Issue by rob-ferg** [SchornacklabSLCU/amfinder#34]
Hello,

I've just finished installing amf and amfbrowser and was able to generate predictions for an image using amf. 

But when I run amfbrowser and try to select the prediction file, I cannot click on the OK button. I've tried clicking, selecting with Enter, and just about every other key on my keyboard. 
My lab mate thinks it is because I am trying to run this on Windows 11. Do you know if there is any way to run this without downgrading to Windows 10? Alternatively I could try installing on a system with Linux.
What is your recommendation?

Thanks,
Robbie
University of Ottawa

**Comment by EEvangelisti** [comment]
Dear Robbie,

Thank you for your interest in AMFinder.

Unfortunately, I have never heard of such an issue, so I can only guess it is a compatibility problem between the graphical system and the OS. The best is to install AMFinder on a Linux machine (it could be a virtual machine). I am happy to help with the installation if needed.

Best regards,
Edouard
