### ISSUE TITLE
AMFinder is not recognizing my photos as "valid archives"

### ISSUE THREAD

**Issue by laurengenetics** [SchornacklabSLCU/amfinder#9]
I have the AMFinder downloaded to a HPC and am trying to run a prediction on 18 photos (which I have converted to JPEG images). When I run my command, the software recognizes the photos but comes back with an error saying they are not valid archives.

**Comment by SchornacklabSLCU** [comment]
Hello, thanks for reporting this. The misleading error message is now corrected.

Are you trying to predict intraradical hyphal structures? If so, you first need to predict colonisation and convert your predictions to annotations using `amfbrowser`. A standard pipeline is as follows:

1. Predict colonisation with `amf predict *jpg`. **Note:** this will create an archive `foo.zip` next to image `foo.jpg`.
2. Convert computer predictions to annotations with the editor (`amfbrowser`). For instance, run `amfbrowser foo.jpg`. This requires a graphical environment (it won't work on an HPC).
3. Predict intraradical structures with `amf predict -2 *jpg` (or, if you want to specify the trained network to use, the command becomes `amf predict -net your_trained_network.h5 *jpg`).

Please let me know if that solves the problem. I will add more documentation to the README soon.

**Comment by laurengenetics** [comment]
Hello,

Thank you for your response to my query. I was attempting to run the
prediction of colonization but the source still is not working even though
I have used the HPC script written on your github resource and assistance
from the IT department at the University of Georgia. I have attached the
command line and response below. I am using JPEG images but the error
states "TypeError: cannot unpack non-iterable NoneType object". I have
tried working with TIFF images and I get the same result. Do the images
need to be in a different format for the prediction? The team that runs the
HPC has the amf browser functioning within an interactive environment but
it is not useful until I have this first step working. Any suggestions you
may have would be greatly appreciated.
[image: image.png]

Best Regards,
Lauren Stupp

**Comment by SchornacklabSLCU** [comment]
Hello,

Sorry to see it is not working yet. For some reason, I cannot access the attachment. Could you please copy/paste the script and error message again? Thanks.

**Comment by laurengenetics** [comment]
I apologize for the lack of access to the photo. I have copied my script
below. Thank you for your help.

(amfenv) ***@***.*** ~$ /work/jaalab/amfinder-2.0/amf/amf predict
--network CNN2v1.h5 /work/jaalab/LaurenStupp/inputfile/amfindertestfile/*
Using TensorFlow backend.
AMFinder script version 2.0
* Input images: 18
* Running in prediction mode
* Pre-trained network:
/work/jaalab/amfinder-2.0/amf/trained_networks/CNN2v1.h5
* Classes: arbuscules (A), vesicles (V), hyphopodia (H), intraradical
hyphae (IH).
* Image Snap-1193.jpeg
WARNING: The file
/work/jaalab/LaurenStupp/inputfile/amfindertestfile/Snap-1193.jpeg is not a
valid archive.
Traceback (most recent call last):
  File "/work/jaalab/amfinder-2.0/amf/amf", line 61, in <module>
    main()
  File "/work/jaalab/amfinder-2.0/amf/amf", line 51, in main
    AmfPredict.run(input_files)
  File "/work/jaalab/amfinder-2.0/amf/amfinder_predict.py", line 231, in run
    table, cams = predict_level2(path, image, nrows, ncols, model)
TypeError: cannot unpack non-iterable NoneType object

**Comment by SchornacklabSLCU** [comment]
I recommend you re-download the sources, the error message and few other things have been corrected. 

Regarding your issue, you are using **CNN2**v1 which predicts intraradical hyphal structures (arbuscules, vesicles, intraradical hyphae). This won't work if you do not use **CNN1** first (either CNN1v1 or CNN1v2). Once CNN1 prediction is done, you will get a file `Snap-1193.zip` next to `Snap-1193.jpeg`. Then, follow the steps I described in my previous message.

**Comment by laurengenetics** [comment]
Thank you! Your suggestion worked perfectly. Such a silly error on my part.
When I am running the graphical interface, I am having trouble uploading
the prediction created by step one. Is this the reason the HPC will not
work with the GUI?

**Comment by SchornacklabSLCU** [comment]
Excellent! To load predictions, you just need to run `amfbrowser image.jpeg`. To display predictions, you need to click on the button Import on the right. Usually, HPC are text-based only so you won't be able to run a graphical interface.

**Comment by SchornacklabSLCU** [comment]
Hello, is your problem solved? Can I close the issue? Thanks.

**Comment by laurengenetics** [comment]
Hello! Yes, I was able to run through all the steps this morning. Thank you
so much for all of your help.

**Comment by SchornacklabSLCU** [comment]
You are welcome
